### ISSUE TITLE
Keycdn (kxcdn.com) is not vulnerable for subdomain takeover

### ISSUE THREAD

**Issue by mzet-** [EdOverflow/can-i-take-over-xyz#112]
## Service name

Content delivery, simplified (https://www.keycdn.com/).

## Documentation

It seems that there is no way to claim dangling CNAME record to `kxcdn.com` entry. As record of kxcdn.com has following structure:

```
<user-provided-input>-<keycdn-user-ID>.kxcdn.com
```
attacker has only control of the first part of the entry (i.e. `<user-provided-input>`) second part is (`<keycdn-user-ID>`) is assigned by the KeyCdn during registration.

**Comment by codingo** [comment]
Closed with #113

**Comment by codingo** [comment]
Also thank-you @mzet-, I was rushing and should have said that initially. This is very appreciated though!

**Comment by Steiner-254** [comment]
haha..nice
