### ISSUE TITLE
Is takeover possible for .exacttarget.com.edgekey.net domains?

### ISSUE THREAD

**Issue by JeppW** [EdOverflow/can-i-take-over-xyz#116]
I've come across a CNAME pointing to a .exacttarget.com.edgekey.net domain that I believe might be vulnerable to subdomain takeover. How does one register a such domain?

**Comment by JvdHout1011** [comment]
edgekey.net is Akamai afaik, of which is not sure it's vulnerable to takeover. 

edgekey.net domains follow the following format: [targetdomain].[tld].edgekey.net. Is there any way you can show this to be vulnerable?

**Comment by Rudraksha-Das** [comment]
Yes, that's my question too, can we takeover an *.*.edgekey.net domain?

**Comment by pdelteil** [comment]
Stop asking and just test it!

**Comment by JeppW** [comment]
I totally forgot about this. I don't think there's any reason this keep this issue open.
