### ISSUE TITLE
domains or subdomains take over for shopify 

### ISSUE THREAD

**Issue by arjunnkn** [EdOverflow/can-i-take-over-xyz#119]
anyone tried recently ?

**Comment by messi96** [comment]
yes, I was able to takeover recently (within last month)

**Comment by arjunnkn** [comment]
reported ? hackerone ?

**Comment by messi96** [comment]
yes, but not h1.. a public BB program org, rewarded too!

**Comment by arjunnkn** [comment]
ok i want to report too . can you share the program with me ??

**Comment by arjunnkn** [comment]
followed you on twitter , can we discusss something there ?

**Comment by messi96** [comment]
sure!

**Comment by arjunnkn** [comment]
@nbackiet am i visible to you there ?
