### ISSUE TITLE
Subdomains takeover via smugmug.com

### ISSUE THREAD

**Issue by arjunnkn** [EdOverflow/can-i-take-over-xyz#121]
S## Service name
Smugmug.com
## Proof
I will put today

**Comment by xorcat** [comment]
I can confirm that this is possible.
Error when vulnerable appears to be 404.
Can sign up for a free trial account, and set "Custom Domain" in account settings.

**Comment by arjunnkn** [comment]
I have complete list of all subdomains that are linked to smugmug shops and are vulnerable , contacted smugmug too but they aren't serious about it

**Comment by tavgar** [comment]
no longer:
https://www.smugmughelp.com/hc/en-us/articles/18212351739284-Use-a-custom-domain
