### ISSUE TITLE
Vulnerabile Shopify stores

### ISSUE THREAD

**Issue by arjunnkn** [EdOverflow/can-i-take-over-xyz#127]
## Service name 
pamleftpamright.com
peterreed.com
pgpromotionalitems.co.uk
piecestopeaces.com
pillowfightfactory.com
pilovilo.com
pitbull-store.co.uk
portraydesigns.com
quantumbassmarket.com
quickmobilefix.com
rayethelabel.com
rdfabrikwerks.com
rebeccaminkoff.com
recoconyc.com
ripdiculous.com
ritualandlore.com
roughneckoutlet.com
sabithestore.us
samayhome.com
sayitwithasock.com.
seasiderug.com
seavees.com
shiokcollaborative.sg
shoewin.com
shop.thegentlemensposse.com
shopsuperdeluxe.com
shopwickliffela.com
simplepaperie.com
simplicitylaser.com
sinnersattire.com
skandiboxes.com
slaworldwide.com
smilingdesignsforkids.com
smithstreetcandles.com
sockittome.com.au
socutesocute.com
songbirdocarina.com
specialeventsparklers.com
spornette898.com
squashabout.com
squat-life.co.uk
squeekyart.com
st-roche.com
storydeals.com
straightfromthebarrel.net
streetgents.com
sugarcityspeedshop.com
suite7seven.com
sun-siesta.com
sundaeriot.com
sweetorange.shop
t2mwireless.com
## Proof
All are vulnerable via Shopify service
## Documentation
Attached

**Comment by melardev** [comment]
I read your message, I am still trying to understand it, can you help me(or us) to understand this?
The worst thing is that I achieved to read 2 domains in that very bad quality picture, and both sites are alive

**Comment by arjunnkn** [comment]
Now ?

**Comment by arjunnkn** [comment]
The report was closed as duplicate , and if you are aware of hackerone rules , they must either merge the duplicate report to the original one or acknowledge the duplicate with the original report Id . They did nothing but said that they knew the issue internally

**Comment by arjunnkn** [comment]
Sorry I submitted this report month ago and all were tested at that time , coz at that time I had 20k domains fully tested . I thought it would be worth testing

**Comment by melardev** [comment]
@arjunnkn 
Ok so what you reported was a design issue to Shopify because their service allows subdomain takeover?
Well, we knew that long ago, indeed if you know the hackerone rules, submitting a duplicate issue will not make any difference on your hackerone points ....
BUT ..... listen to this:
Submitting a report that is a duplicate of a known issue MAKES you lose points, so you actually should have lost points there, because this is a very known issue for all of us, however, you still went ahead and reported it to Shopify.
Source : https://docs.hackerone.com/hackers/reputation.html

Hint: the trick is on the table of that hackerone docs page.
Hint 2: You should have lost 5 points

**Comment by arjunnkn** [comment]
All were vulnerabile to subdomain takeover that too wildcard one that gives countless subdomains takeover at once per domains

This is misconfiguration at client end but when Shopify is allowing a non parent domain owner to takeover any other parent subdomain it's Shopify issue

**Comment by arjunnkn** [comment]
![Screenshot_20191220-000335](https://user-images.githubusercontent.com/14961110/71199609-4b417b00-22bc-11ea-8837-f466b0ac7cb9.png

Noone reported this issue to Shopify via hackerone platform  . Shopify confirmed it to me I can show you 

Moreover I didn't loose a single reputation on it . Trick

**Comment by arjunnkn** [comment]
@melardev  what you got  as response from hackerone for your shopify submission ?

**Comment by codingo** [comment]
This is outside the remit of this repository. Further posting of vulnerable sites will lead to a ban.
