### ISSUE TITLE
Unsure about Akamai

### ISSUE THREAD

**Issue by sa7mon** [EdOverflow/can-i-take-over-xyz#13]
There have been a few subdomains that I've come across now that look like this:
`Server: AkamaiGHost`
and the page will say:
<pre>Invalid URL
The requested URL "[no URL]", is invalid.</pre>

As far as I can tell, this message is coming from Akamai, I'm assuming from their CDN service unless they have others? Does anyone know if this vulnerable to a takeover?

**Comment by codingo** [comment]
@sa7mon I'm on most slacks/mattermost in some capacity. Could you ping me where you are and I'll work through this with you? Happy for you to claim the bounty, I'll just walk you through the (potential) takeover and if it works we can circle back and update the documentation here.

**Comment by codingo** [comment]
Previously confirmed that this is not possible and subsequently closing this report.

**Comment by 4v1raj** [comment]
I found some subdomains that look like this:
Server: edgesuite and akadns (Akamai)
I found some different 404 responses for those subdomains 
look like :
1>File not found."

2>Service Unavailable - DNS failure
The server is temporarily unable to service your request. Please try again later.

3>An error occurred while processing your request.

This is what I getting from that Akamai CDN service 
which is other the last one 

Invalid URL
The requested URL "[no URL]", is invalid.

Does anyone know if this vulnerable to a takeover?

**Comment by gowthamss** [comment]
I have come across the same issue i.e, with akamai , but when I'm trying to create an account it is asking for business email and company name. And I don't have one. How can I proceed further.

**Comment by gowthamss** [comment]
Were u able to takeover the subdomain you are targeting. If yes, requesting you to guide me through.

**Comment by jareddarkweb** [comment]
I found a domain that returns a ngnix 404 page not found and points to akamaie not takeoverable?

**Comment by vis-dot** [comment]
the subdomain i found is currently inactive and it is pointing to akamai tech but i couldn't register an account there...how to proceed further to take over the account?

**Comment by lCyPh3r** [comment]
[test](http://%@_)

**Comment by f0rhacksd** [comment]
<button onclick=alert('xss')>click me</button>

**Comment by f0rhacksd** [comment]
<button onclick=alert('xss')>click me</button>

**Comment by f0rhacksd** [comment]
[<button onclick=alert('xss')>click me</button>](url)

**Comment by tavgar** [comment]
[-](url)

**Comment by RECING21** [comment]
so do we know if akamai is vulnerable to takeover ?

**Comment by f0rhacksd** [comment]
I think akami is impossible to takeover
