### ISSUE TITLE
Cloud Flare Error (403 ERROR) vuln or no

### ISSUE THREAD

**Issue by knassar702** [EdOverflow/can-i-take-over-xyz#131]
## Hi Guys when visit domain i found this error

![1](https://user-images.githubusercontent.com/45688522/73562234-5e22a000-4463-11ea-947c-65eba70bb361.png)

# Can i Takeover it ??

**Comment by codingo** [comment]
This is overly documented already over this repo. In short, no, no public takeover is presently noted.
