### ISSUE TITLE
Mashery

### ISSUE THREAD

**Issue by random-robbie** [EdOverflow/can-i-take-over-xyz#14]
Since the H1 report it's no longer possible to take over the domain.
[![Capture.png](https://s7.postimg.cc/50x6etvmz/Capture.png)](https://postimg.cc/image/qakspobxj/)

**Comment by ttymeh** [comment]
Mashery no longer lets trial users add custom domains. I believe a paid user can though.

**Comment by ttymeh** [comment]
Starting at $1995/month

**Comment by codingo** [comment]
Addressed in #15 and #16 (one for title and one for long description).

**Comment by codingo** [comment]
Resolved via #54

**Comment by codingo** [comment]
These do appear to be vulnerable now with a paid account. Although Mashery seeks account approval manually, once the account is paid this does not include any sort of company verification (such as a company e-mail, or A record).

**Comment by m3chboy** [comment]
Any update on this?

**Comment by valaDevs** [comment]
Is there any update on this issue?
