### ISSUE TITLE
are subdomains pointing to akamaiedge.net takeover-able?

### ISSUE THREAD

**Issue by ronykris** [EdOverflow/can-i-take-over-xyz#161]
## Service name
akamaiedge.net

## Proof
Below is the answer from dig abc.xyz.com
;; ANSWER SECTION:
abc.xyz.com	899	IN	CNAME	dpp-dmo-wc.edgekey.net.
dpp-dmo-wc.edgekey.net.	359	IN	CNAME	e29511.dscb.akamaiedge.net.
e29511.dscb.akamaiedge.net. 19	IN	A	106.51.42.35
e29511.dscb.akamaiedge.net. 19	IN	A	106.51.42.10

The subdomain abc.xyz.com gave an invalid URL

Invalid URL
The requested URL "[no URL]", is invalid.

Reference #9.1f2a336a.1595680606.568fa086  

Need help, is this domain takeover-able?

**Comment by adityathebe** [comment]
#13

**Comment by Steiner-254** [comment]
~ I dont think it's a vulnerability.
