### ISSUE TITLE
Take Over the domain equinix1a.xyz

### ISSUE THREAD

**Issue by artrebultan21** [EdOverflow/can-i-take-over-xyz#190]
## Service name
Take Over
## Proof
UDPR violation - infridgement against Equinix.com trademark
## Documentation
http://equinix1a.xyz (parked domain)

**Comment by EdOverflow** [comment]
I am not quite sure I understand this one. Is this a service that allows for hosting of websites with a custom hostname or are you linking to a parked domain?

**Comment by artrebultan21** [comment]
Sorry, please ignore this. Just thought you are doing TakeOver services.

Thank you for reaching-out.

Warmest regards,
-Mike

Sent from my iPhone

On 3 Feb 2021, at 9:29 PM, EdOverflow <notifications@github.com> wrote:

﻿

I am not quite sure I understand this one. Is this a service that allows for hosting of websites with a custom hostname or are you linking to a parked domain?
