### ISSUE TITLE
Todayisnew AKA eric Submitted a cloudfront takeover 

### ISSUE THREAD

**Issue by harvardstudent2020** [EdOverflow/can-i-take-over-xyz#199]
## proof: https://hackerone.com/reports/352869
how was this even possible?

**Comment by ethrx** [comment]
The report was originally submitted 3 years ago. If you actually read the report he says:
> Cloudfront was vulnerable in the past, no longer from my experience.

7 days ago for a disclosure request.

**Comment by harvardstudent2020** [comment]
damn. alright just noticed that. so cloudfront is done n dusted.

**Comment by ethrx** [comment]
yepppp maybe some other amazon services are still vulnerable, though unlikely.
