### ISSUE TITLE
Create a list of services that have not been tested yet.

### ISSUE THREAD

**Issue by EdOverflow** [EdOverflow/can-i-take-over-xyz#21]
We could integrate a TO-DO list into the README.md file for services that have not been tested yet. That way, people can help us expand the list by focusing on untested services.

**Comment by codingo** [comment]
Should we leave these as open issues instead (such as #24)? I think most people would look to issues for ways to contribute and this might get missed if it's in the readme.

**Comment by bluedangerforyou** [comment]
I've tested 000webhost and it is not possible. They do not allow creating name that was used, then deleted, they mention in their support page they don't allow for security reasons 

https://www.000webhost.com/website-faq/how-to-modify-my-username-or-domain-1

Crap service, not sure if companies use this. But I wanted to help
