### ISSUE TITLE
Github Subdomain Takeover not possible!

### ISSUE THREAD

**Issue by umar98** [EdOverflow/can-i-take-over-xyz#227]
Site: sub.example.com
Cname pointing to xyz.github.io (which also shows a 404 page).

Created a repo with xyz, added the custom domain name to sub.example.com

Error: The CNAME `sub.example.com` is already taken. Check out https://docs.github.com/articles/troubleshooting-custom-domains#cname-errors for more information.

**Comment by EdOverflow** [comment]
Closed in favour of #217.
