### ISSUE TITLE
Subdomain Takeover Pointing to Blogger

### ISSUE THREAD

**Issue by StefanTobler** [EdOverflow/can-i-take-over-xyz#236]
## Proof

<img width="517" alt="Screen Shot 2021-09-19 at 2 38 30 AM" src="https://user-images.githubusercontent.com/22108632/133918245-955c2fe5-a7e9-491c-83ea-fb32d2d5b0e2.png">

## Documentation

Dangling (sub)domains that point to ghs.google.com usually point to a Blogger instance. However, this subdomain cannot be taken over because Blogger requires a security CNAME record for a domain to point to the blogger instance, not just the fact that ghs.google.com is registered as a CNAME.

**Comment by Steiner-254** [comment]
Haha, interesting!

**Comment by victim29** [comment]
[Uploading xss (2) (1).pdf…]()
