### ISSUE TITLE
Wix.com - not Vulnerable 

### ISSUE THREAD

**Issue by vijithvellora** [EdOverflow/can-i-take-over-xyz#245]
## Service name

Wix.Com - Not vulnerable.

## Proof

![xyz takeover not possible for wix](https://user-images.githubusercontent.com/53208145/141080664-ac37ad85-6aba-48cd-a4c5-65eac2bd87ff.png)

If the domain is already parked in wix.com, then it's not possible to take over that.

## Documentation

No documentations found,

**Comment by EdOverflow** [comment]
Closing in favour of https://github.com/EdOverflow/can-i-take-over-xyz/issues/231.
