### ISSUE TITLE
Does  subdomain with eloqua cloud could takeover?

### ISSUE THREAD

**Issue by whiteHat001** [EdOverflow/can-i-take-over-xyz#25]
Does  subdomain with eloqua cloud could takeover?And how to use azure cloud to takeover sudomains?

**Comment by codingo** [comment]
Hi @whiteHat001,

What have you tried? It's difficult to give you good advise if you haven't exposed your thought process and what you've tried already.

There's a number of write-ups on Azure takeovers you can refer to, and I'll add it to this page soon. I'd also recommend trying to do an eloqua takeover yourself - that's normally the first step to learning how to do these and identifying if the're vulnerable or not.
