### ISSUE TITLE
Subdomain takeover on Cname simplifyemail.com  

### ISSUE THREAD

**Issue by barhaam** [EdOverflow/can-i-take-over-xyz#305]
Hi guys need help with a subdomain alias to `CNAME eu-proxy-2.symplifymail.com`

**Comment by pdelteil** [comment]
Hi,

You need to provide more details in order to understand what you want to do.  Are you getting a dns response `NXDOMAIN` ?

**Comment by barhaam** [comment]
It shows a 200 http status
![image](https://user-images.githubusercontent.com/102578146/202758733-854c49c9-c3de-4cf7-b0db-b64b95911170.png)

**Comment by pdelteil** [comment]
> It shows a 200 http status ![image](https://user-images.githubusercontent.com/102578146/202758733-854c49c9-c3de-4cf7-b0db-b64b95911170.png)



This is just a `nginx` default page. You should investigate more about how subdomain takeovers work.
