### ISSUE TITLE
Shopify Real Check with REST API

### ISSUE THREAD

**Issue by buckhacker** [EdOverflow/can-i-take-over-xyz#32]
## Service name
Shopify

## Proof
1) Page must contain: Sorry, this shop is currently unavailable.
2) CNAME must contain: myshopify.com or shops.myshopify.com
3) REST API Query must answer with: "status":"available"

Please read the docs for more details.

## Documentation
I wrote a long article and release a small script that performs three types of test (page error message, CNAME and REST API query). 
https://medium.com/@thebuckhacker/how-to-do-55-000-subdomain-takeover-in-a-blink-of-an-eye-a94954c3fc75
https://github.com/buckhacker/SubDomainTakeoverTools/blob/master/ShopifySubdomainTakeoverCheck.py

**Comment by codingo** [comment]
I'm familiar with your article / repository - quite a fan of this work (cottoned onto it early via a Github watch).

I'll review this shortly.

**Comment by codingo** [comment]
Resolved in #33

**Comment by Techbrunch** [comment]
A potentially interesting case:

```
ftp.target.com.		2236	IN	CNAME	target.com.
target.com.		44	IN	A	23.227.38.65
www.target.com.		28	IN	CNAME	target2.myshopify.com.
target2.myshopify.com.	1928	IN	CNAME	shops.myshopify.com.
shops.myshopify.com.	15	IN	A	23.227.38.74
```

target.com redirects to www.target.com (301)

In Shopify target.com and www.target.com were not available but ftp.target.com was and I was able to takeover the subdomain.

**Comment by Attacker991** [comment]
"Upon visiting the domain, I received the message "Sorry, this store is currently unavailable." However, Shopify indicates that the same domain, flagged as vulnerable to takeover by Nuclei, is currently in use. Can someone clarify this discrepancy and its implications for subdomain security assessment?"

**Comment by Rezy-Dev** [comment]
Not vulnerable anymore:
<img width="1148" height="839" alt="Image" src="https://github.com/user-attachments/assets/375c177d-b9cb-4206-ab51-58e00318d108" />

**Comment by charmedai** [comment]
I can also confirm shopify is not vulnerable anymore requires a TXT verification

<img width="722" height="542" alt="Image" src="https://github.com/user-attachments/assets/c7f67240-c4a8-4b2e-ac97-82a79bef30c5" />
