### ISSUE TITLE
GitHub Pages proofs

### ISSUE THREAD

**Issue by PatrikHudak** [EdOverflow/can-i-take-over-xyz#37]
## Service name
GitHub Pages

## Proof

GitHub uses virtual hosting identical to other cloud services. The site needs to be specified _explicitly_ in domain settings. Step-by-step process:

1. Go to [new repository](https://github.com/new) page
2. Set *Repository name* to canonical domain name (i.e., {something}.github.io from CNAME record)
3. Click *Create repository*
4. Push content using git to a newly created repo. GitHub itself provides the steps to achieve it
5. Switch to *Settings* tab
6. In *GitHub Pages* section choose *master branch* as source
7. Click *Save*
8. After saving, set *Custom domain* to source domain name (i.e., the domain name which you want to take over)
9. Click *Save*

For screenshots, please refer to https://0xpatrik.com/takeover-proofs/.

To verify:
```
http -b GET http://{DOMAIN NAME} | grep -F -q "<strong>There isn't a GitHub Pages site here.</strong>" && echo "Subdomain takeover may be possible" || echo "Subdomain takeover is not possible"
```

(Note: DOMAIN NAME has to be the affected domain, not the `github.io` page itself. This is due to Host header forwarding which affects the HTTP response)

## Documentation

There is only one format of GitHub Pages domains:

- *.github.io

please note that having CNAME to `github.io` itself can also lead to subdomain takeover.

**Comment by PatrikHudak** [comment]
Official GitHub Pages docs: https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by codingo** [comment]
Closing as now available on main readme.

**Comment by sumgro** [comment]
Not able to takeover a subdomain pointing to GitHub.io. Error with CNAME is already taken.

snapshot attached.

Is GitHub takeover still working for anyone?

![Screenshot 2019-03-23 at 1 41 20 PM](https://user-images.githubusercontent.com/11391119/54863702-e29b9100-4d71-11e9-97b2-887eebe6869f.jpg)

**Comment by kishoretrommer** [comment]
> 
> 
> Not able to takeover a subdomain pointing to GitHub.io. Error with CNAME is already taken.
> 
> snapshot attached.
> 
> Is GitHub takeover still working for anyone?
> 
> ![Screenshot 2019-03-23 at 1 41 20 PM](https://user-images.githubusercontent.com/11391119/54863702-e29b9100-4d71-11e9-97b2-887eebe6869f.jpg)

Facing the same issue.

**Comment by sumgr0** [comment]
Is it possible to takeover githubapp.com subdomains with github.io CNAME?

**Comment by ravkishu** [comment]
Hi @sumgr0 

I'm not quite sure but you should be able to, because it's not allowed only in case of `github.io, github.com, or github.page` as per official error I'm currently getting.
![image](https://user-images.githubusercontent.com/39808656/102774908-e5e20780-43b1-11eb-9d2a-5532b35beed7.png)


There isn't any such notice regarding `githubapp.com`. So, I suppose you should be able to takeover if it's available.

For more you can head over to https://docs.github.com/articles/setting-up-your-pages-site-repository/

**Comment by NetanMangal** [comment]
Hi @EdOverflow 
I am trying to takeover subdomain **<organization>.github.io** but when I create a repo and try to serve it via the Github Pages, I get a URL like **netanmangal.github.io/<repo-name>**.

Github has started to appending the username to the github.io/<repo-name>

I have done something wrong or I think github pages are no longer vulnerable unless the user/organization have totally deleted their account.

**Comment by h3cksamrat** [comment]
CNAME already taken error occurs in once already created repo and attached cname, so as my understanding *.github.io is not available for takeover.
https://github.community/t/the-cname-is-already-taken/149785

**Comment by monikasharma47** [comment]
anything.github.io   like this github account can we takeover or not

**Comment by monikasharma47** [comment]
anything.github.io   like this github account can we takeover or not  ?

**Comment by Abhaysoft-inc** [comment]
I was still able to takeover a domain

**Comment by Notselwyn** [comment]
Still works. +1

Looks like it's kind of conditional because it can say that the domain is claimed

**Comment by Elgllad99** [comment]
> I was still able to takeover a domain

how you can takeover yet I have some of the vulnerable URLs, if you can help me..

**Comment by Akincibor** [comment]
There is a new beta feature, every custom domain need to be verified. So Github is no more vulnerable.

**Comment by Akincibor** [comment]
<img width="741" alt="Capture d’écran 2022-04-21 à 21 52 19" src="https://user-images.githubusercontent.com/99909324/164541836-d483aa91-b4cf-4921-a81b-43824523caeb.png">


https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization

**Comment by jbreed** [comment]
@akincibor As mentioned, I ran into this specific issue where it required me to verify the domain by inserting a domain txt entry for verification on my account before I could add the custom domain to a repo. 

Do we know if this is always the case for subdomain takeovers via github.io, or only specific domains with a feature enabled?

**Comment by sumgr0** [comment]
I've experienced the same with Github takeovers in the last couple of days. Looks like github has implemented it across the board.

**Comment by IrresistibleKhan** [comment]
> @akincibor As mentioned, I ran into this specific issue where it required me to verify the domain by inserting a domain txt entry for verification on my account before I could add the custom domain to a repo.
> 
> Do we know if this is always the case for subdomain takeovers via github.io, or only specific domains with a feature enabled?

I found a subdomain pointing to xyz.github.io,  and it is vulnerable, but when trying to set it as the vulnerable subdomain as the  custom domain it asks to insert a txt entry for verification.
Is there any way to takeover such a domain?

**Comment by pdelteil** [comment]
> > @akincibor As mentioned, I ran into this specific issue where it required me to verify the domain by inserting a domain txt entry for verification on my account before I could add the custom domain to a repo.
> > Do we know if this is always the case for subdomain takeovers via github.io, or only specific domains with a feature enabled?
> 
> I found a subdomain pointing to xyz.github.io, and it is vulnerable, but when trying to set the vulnerable subdomain as the custom domain it asks to insert a txt entry for verification. Is there any way to takeover such a domain?

Then, it's not vulnerable.

**Comment by A7BIL** [comment]
i found a vulnerable xx.github.io subdmain but when i try to add the domain to a new repository, i get this message
The custom domain `xxxxx.domain.com` is already taken.
any solution ?

**Comment by sa1tama0** [comment]
:warning::warning: GitHub's pages are now **secure** and **no longer vulnerable**. :warning::warning:
GitHub has implemented DNS verification to confirm the legitimacy of domains.


![GitHub](https://user-images.githubusercontent.com/113327308/206844071-55fe8f71-ede7-4caf-9daf-803b15a48138.png)

**Comment by EdOverflow** [comment]
> ⚠️⚠️ GitHub's pages are now **secure** and **no longer vulnerable**. ⚠️⚠️ GitHub has implemented DNS verification to confirm the legitimacy of domains.
> 
> ![GitHub](https://user-images.githubusercontent.com/113327308/206844071-55fe8f71-ede7-4caf-9daf-803b15a48138.png)

This does not apply to retrospective custom domains, right?

**Comment by akincibor** [comment]
I thought Github was no longer vulnerable to STO but actually I managed to take a subdomain.

**Comment by pdelteil** [comment]
> I thought Github was no longer vulnerable to STO but actually I managed to take a subdomain.

How?

**Comment by dadsgone0** [comment]
What if there is a 404 no pages site here error, but the account that owns it still exists? like if example30.github.io would 404, but the example30 account still existed, would it be vulnerable?

**Comment by corneliusroemer** [comment]
I confirm that the vulnerability still exists, at least for domains without domain verification. Example: turakhia.ucsd.edu

**Comment by cyberduck404** [comment]
```
You must verify your domain REDACTED.com before being able to use it. Check out https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages for more information.
```
Is it safe now?

**Comment by cyberduck404** [comment]
Confirmed, still be vuln.

**Comment by Paulino123p** [comment]
![image](https://github.com/EdOverflow/can-i-take-over-xyz/assets/112760488/4f3af881-9677-4664-a9be-065f4f39b944)

**Comment by Paulino123p** [comment]
You must verify your domain dev-test.***** before you can use it. Check out https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages for more information.

**Comment by inteleon404** [comment]
[![▶ Play Video](https://img.youtube.com/vi/hUMe_hkwLGQ/maxresdefault.jpg)](https://www.youtube.com/watch?v=hUMe_hkwLGQ)
