### ISSUE TITLE
Squarespace ( is this possible for subdomain takeover)

### ISSUE THREAD

**Issue by PH-Apolonio** [EdOverflow/can-i-take-over-xyz#388]
## Service name
Squarespace
## Proof
![Screenshot 2023-10-31 174840](https://github.com/EdOverflow/can-i-take-over-xyz/assets/74172849/920cc5e5-e0fa-46f5-a9ab-7d67db9b78df)

## Documentation

is this possible for subdomain takeover?

 when i tried  to connect the subdomain to my domain it says " This website is pending domain owner verification
To learn how to verify your domain"

**Comment by knowthetech** [comment]
not possible

**Comment by PH-Apolonio** [comment]
> not possible

thanks for info

**Comment by earthenvessel** [comment]
For reference, Squarespace documentation explains the verifications steps here: https://support.squarespace.com/hc/en-us/articles/206542017-Connecting-a-third-party-subdomain-to-your-Squarespace-site

It requires proving ownership of the domain by creating a new CNAME DNS record that points to verify.squarespace.com.
