### ISSUE TITLE
Unable to determine the correct region to create S3 bucket for subdomain takeover.

### ISSUE THREAD

**Issue by crazymonk007** [EdOverflow/can-i-take-over-xyz#410]
While working on a bug bounty, I found a subdomain was vulnerable to subdomain takeover via an AWS S3 bucket. I created a bucket with the same name and uploaded an HTML file to take over the subdomain. However, when I visited the domain after creating the bucket, I encountered the following error:

<img width="960" alt="Untitled" src="https://github.com/EdOverflow/can-i-take-over-xyz/assets/137065986/50aec41b-ca57-4eb3-8732-aa13bf65bfe1">

The error indicates that `us-west-2` is the incorrect endpoint, meaning I created the bucket in the wrong region. To identify the correct region, I used `nslookup` and `dig`, which provided me with 2 IPs that are not included in https://ip-ranges.amazonaws.com/ip-ranges.json.

Any help would be appreciated.

**Comment by pdelteil** [comment]
Hello there, 

First, don't share your target details. 
Second, brute force the region of the bucket: Create it in different regions until it works.

**Comment by crazymonk007** [comment]
> Hello there,
> 
> First, don't share your target details. Second, brute force the region of the bucket: Create it in different regions until it works.

Thanks for the tip bro, i am new to this world.
I am bruteforcing currently, but before trying again there is a waitup period of around 1 hour, and i am finding this way too inefficient, so i was wondering if a more efficient way was possible

**Comment by pdelteil** [comment]
Often times is more than 1 hour. Just script it and let it run.

**Comment by crazymonk007** [comment]
> Often times is more than 1 hour. Just script it and let it run.

Well, I am not a big coder, and AI ain't that good, so i can't write a script, I guess I will need to manually bruteforce.

**Comment by pdelteil** [comment]
Not really taking tips.... 🤣

**Comment by crazymonk007** [comment]
> Not really taking tips.... 🤣 

Not that I don't want to.

**Comment by crazymonk007** [comment]
> > Not really taking tips.... 🤣
> 
> Not that I don't want to.

I bruteforced it and was successful in taking over the domain after a few unsuccessfull attempts.
