### ISSUE TITLE
subdomain takeover cloudfront

### ISSUE THREAD

**Issue by moe91** [EdOverflow/can-i-take-over-xyz#61]
## Service name
Hi, I check many sites daily of this security vulnerability and extracted many subdomains and while trying to register it is a problem as in the image of the solution
![1 p2l3697uaa7mxkb6vng8yw](https://user-images.githubusercontent.com/44072994/47554814-e3d7a780-d912-11e8-9803-57dfc5dcf486.png)

**Comment by codingo** [comment]
This is still possible in some circumstances (such as when the cname is pointed twice). On my phone but I'll update appropriaty soon.

**Comment by moe91** [comment]
> 
> 
> This is still possible in some circumstances (such as when the cname is pointed twice). On my phone but I'll update appropriaty soon.

I did not understand did you mean that there is a skip through a phone, for example, or you will download an update soon to overcome this problem

**Comment by codingo** [comment]
This is better explained in #29
