### ISSUE TITLE
Ask about response

### ISSUE THREAD

**Issue by radenvodka** [EdOverflow/can-i-take-over-xyz#70]
can a response like the one below take over?

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t A 0day.xxxxx.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 12015
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;0day.xxxxx.com.             IN      A

;; AUTHORITY SECTION:
0day.xxxxx.com.           900     IN      SOA     ns-xxx.awsdns-61.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 62 msec
;; SERVER: 192.168.xx.xx#53(192.168.xx.xx)
;; WHEN: Fri Nov 23 18:53:17 DST 2018
;; MSG SIZE  rcvd: 130

**Comment by codingo** [comment]
Closing. This is for maintaining contributions, not a support desk. You should include information of what you've tried, what happened, what your suspicions are. This currently is just trying to get somebody else to do all of the work for you.

Try harder.

**Comment by ericnyamu1** [comment]
ofcourse NOT.there's no cname for takeover.
