### ISSUE TITLE
subdomain Takeover through wordpress.com 

### ISSUE THREAD

**Issue by ziak2677** [EdOverflow/can-i-take-over-xyz#81]
This Issue is vulnerable or not?

(Warning! Domain mapping upgrade for this domain not found. Please log in and go to the Domains Upgrades page of your blog to use this domain.) 

If vulnerable then how i takeover through wordpress

**Comment by hakluke** [comment]
@ziak2677 it sounds like the domain has been mapped to an existing Wordpress account, but that account does not have domain mapping enabled. If this is the case, the domain is not vulnerable.

If the Wordpress takeover is possible, it will display the text `Do you want to register *.wordpress.com?`, as outlined in https://github.com/EdOverflow/can-i-take-over-xyz
