### ISSUE TITLE
is bookbaby is Vulnerable or not ?

### ISSUE THREAD

**Issue by AhmedOzil10** [EdOverflow/can-i-take-over-xyz#87]
## Bookbaby
 
I found a subdomain with CNAME has records to  Bookbaby records and doesn't belong to the main Subdomain Records 
After I dig A making sure that it's possible to Subdomain Takeover but is that Really Vulnerable or Not ?

**Comment by codingo** [comment]
Have you tried / tested it? The intention of this repository is a documentation of knowledge, but not a support desk where this is verified for you.
