### ISSUE TITLE
Requested : Salesforce Desk (desk.com)

### ISSUE THREAD

**Issue by xsuperbug** [EdOverflow/can-i-take-over-xyz#9]
It seems subdomains can be taken over, I think. Can you check it?

**Comment by its0x08** [comment]
any specific subdomain ?!

**Comment by xsuperbug** [comment]
Sorry, I have to censor it. A screenshot is as follows : 
http://oi67.tinypic.com/27x48bp.jpg

**Comment by EdOverflow** [comment]
Resolved in #10; thank you.

**Comment by abiralS** [comment]
Is subdomain takeover still possible for desk ? Have have not been able to create desk account after sales force bought i.

**Comment by codingo** [comment]
Hi @abiralS @xsuperbug, this state has now been changed as per #50

**Comment by pdelteil** [comment]
> i think it vulnerable --> https://hackerone.com/reports/201796

Hello,

That report is 6 years old. That's not enough to still consider it as valid/vulnerable.
